# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{user}.github.io/your_lib/"

git_url = "https://github.com/{user}/your_lib/tree/{branch}/"

def custom_doc_links(name): return None
